# Generated by Django 5.0.6 on 2024-06-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_created_date_blog_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_date',
        ),
    ]
