# Generated by Django 5.0.6 on 2024-06-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_blog_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='draft',
        ),
    ]
