# Generated by Django 5.0.6 on 2024-06-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blog_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_date',
        ),
    ]
